### ISSUE TITLE
Turn Order -lose conditions

### ISSUE THREAD

**Issue by martintseng** [laihaotao/COMP354#18]
Each turn, you may play 1 energy card, 1 Trainer Card (unless it is an item, then it is infinite), and a Pokemon Card.

Once the turn is done, we need to check the win conditions, and the lose conditions.

**Comment by laihaotao** [comment]
I think we only need to check the win condition, which is done. Working on the limit the operation time in a turn.

**Comment by laihaotao** [comment]
still have problems about the attack limitation, leave it to Frederic....

**Comment by laihaotao** [comment]
tempory fixed
