### ISSUE TITLE
Attack can attack two pokemon

### ISSUE THREAD

**Issue by laihaotao** [laihaotao/COMP354#21]
<img width="999" alt="screen shot 2017-06-03 at 12 14 16" src="https://cloud.githubusercontent.com/assets/12627863/26755192/5b62b30c-4856-11e7-9412-999de766042c.png">

In this scenario, I click abilities [Stretch kick](https://github.com/laihaotao/COMP354/blob/master/src/main/resources/abilities.txt#L59):

> Stretch Kick:dam:target:choice:opponent-bench:30

the following thing pops up, which it correct, but the active Pokemon **also suffer the damage**.

<img width="998" alt="screen shot 2017-06-03 at 12 14 01" src="https://cloud.githubusercontent.com/assets/12627863/26755191/596070b2-4856-11e7-824b-0e362f264cbf.png">

**Comment by FredericDesgreniers** [comment]
This was the result of a switch statement not having a break. It should be solved
