### ISSUE TITLE
prize card amount incorrect

### ISSUE THREAD

**Issue by laihaotao** [laihaotao/COMP354#9]
The prize card amount should be initialized as 6, which is 7 now.

Please check the rule [here](https://github.com/laihaotao/COMP354/wiki/Rule#setting-up-to-play)

Please check out and run the [test case](https://github.com/laihaotao/COMP354/blob/master/src/test/java/game/GameStartTest.java)

**Comment by FredericDesgreniers** [comment]
This has been fixed. A for loop in player was doing 0 through 6 instead of 0 through 5, which was putting one card too many in the prize cards.
